# Generated by Django 5.0.1 on 2024-03-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_name_staff_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='username',
            new_name='name',
        ),
    ]
