# Generated by Django 5.0.1 on 2024-03-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_staff_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
