# Generated by Django 5.0.1 on 2024-03-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_staff_profile_image_staff_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='profile_images/'),
            preserve_default=False,
        ),
    ]
