# Generated by Django 5.0.1 on 2024-03-19 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_staff_profile_pic_staff_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='profile_image',
        ),
    ]
