# Generated by Django 5.0.1 on 2024-03-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_course_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
