# Generated by Django 5.0.1 on 2024-03-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_staff_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
