# Generated by Django 5.0.1 on 2024-03-21 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.staff'),
            preserve_default=False,
        ),
    ]
