# Generated by Django 5.0.1 on 2024-03-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_course_course_image_alter_staff_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='password1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='password2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
