# Generated by Django 5.0.1 on 2024-03-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_staff_user_alter_student_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
