# Generated by Django 5.0.1 on 2024-03-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_staff_email_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_password',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
