# Generated by Django 5.0.1 on 2024-03-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_rename_staff_password_staff_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='staff',
            name='password2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
