# Generated by Django 5.0.1 on 2024-03-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_remove_staff_password1_remove_staff_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
