# Generated by Django 5.0.1 on 2024-03-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_remove_staff_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_profile_images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile_images/'),
        ),
    ]
