# Generated by Django 5.0.1 on 2024-03-30 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_choice',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questions',
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.question')),
            ],
        ),
    ]
