# Generated by Django 5.0.1 on 2024-03-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_rename_correct_choice_question_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
    ]
