# Generated by Django 5.0.1 on 2024-03-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_rename_question_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
