# Generated by Django 5.0.1 on 2024-03-31 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_choice_is_correct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
