# Generated by Django 5.0.1 on 2024-03-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_question_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
