# Generated by Django 5.0.1 on 2024-03-31 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
