# Generated by Django 5.0.1 on 2024-04-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
