# Generated by Django 5.0.1 on 2024-04-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_notification_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
    ]
