# Generated by Django 5.0.1 on 2024-04-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_remove_notification_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
    ]
