# Generated by Django 5.0.1 on 2024-04-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_rename_text_choice_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='text',
        ),
    ]
