# Generated by Django 5.0.1 on 2024-04-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_rename_choice_choice_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
    ]
