# Generated by Django 5.0.1 on 2024-03-23 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0024_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_image', models.ImageField(upload_to='Course_images/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=250)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.staff')),
            ],
        ),
    ]
