# Generated by Django 5.0.4 on 2024-04-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='staff',
        ),
    ]
