# Generated by Django 5.0.4 on 2024-04-09 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_staff_profile_image_student_profile_image'),
        ('home', '0005_delete_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.staff'),
            preserve_default=False,
        ),
    ]
