# Generated by Django 5.0.1 on 2024-03-28 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_staff_profile_image_student_profile_image'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='staff_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(),
        ),
    ]
