# Generated by Django 5.0.4 on 2024-04-09 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
    ]
