# Generated by Django 5.0.4 on 2024-04-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_video_description_remove_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.FileField(upload_to=''),
        ),
    ]
