# Generated by Django 5.0.4 on 2024-04-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_video_title_alter_video_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(),
        ),
    ]
